[project]
name = "pdga-data"
version = "0.1.0"
description = "PDGA data collector and API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pandas>=2.2.3",
    "pydantic>=2.10.4",
    "rich>=13.9.4",
    "selectolax>=0.3.27",
]
